[project]
name = "python-sdwan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
    "requests>=2.32.4",
    "simple-term-menu>=1.6.6",
    "tabulate>=0.9.0",
    "urllib3>=2.5.0",
]
